import type { Finding } from '../rules/types';
import type { Summary } from './build';
import { groupFindings, groupWhere } from './group';

const MAX_ROWS = 100;
const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

export function toMarkdown(findings: Finding[], summary: Summary): string {
  const s = summary.bySeverity;
  const lines = [
    `### molfar_audit report — ${s.critical} critical, ${s.warning} warning, ${s.possible} possible, ${s.info} info`,
    '',
    '| Level | Rule | Where | Problem |',
    '|---|---|---|---|',
  ];
  const groups = groupFindings(findings);
  for (const g of groups.slice(0, MAX_ROWS)) lines.push(`| ${g.finding.severity} | ${g.finding.rule} | ${cell(groupWhere(g) || '—')} | ${cell(g.finding.message)} |`);
  if (groups.length > MAX_ROWS) lines.push('', `…and ${groups.length - MAX_ROWS} more.`);
  lines.push('', '_Generated by [molfar_audit](https://github.com/molfarlabs/molfar_audit) · Molfar Labs_');
  return lines.join('\n');
}
