import type { Finding } from '../rules/types';
import type { Summary } from './build';

const MAX_ROWS = 100;
const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

export function where(f: Finding): string {
  return [f.resource, f.file].filter(Boolean).join('/') + (f.line ? `:${f.line}` : '');
}

export function toMarkdown(findings: Finding[], summary: Summary): string {
  const s = summary.bySeverity;
  const lines = [
    `### molfar_audit report — ${s.critical} critical, ${s.warning} warning, ${s.possible} possible, ${s.info} info`,
    '',
    '| Level | Rule | Where | Problem |',
    '|---|---|---|---|',
    ...findings.slice(0, MAX_ROWS).map((f) => `| ${f.severity} | ${f.rule} | ${cell(where(f) || '—')} | ${cell(f.message)} |`),
  ];
  if (findings.length > MAX_ROWS) lines.push('', `…and ${findings.length - MAX_ROWS} more.`);
  lines.push('', '_Generated by [molfar_audit](https://github.com/molfarlabs/molfar_audit) · Molfar Labs_');
  return lines.join('\n');
}
